### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by tamaso** [openlawdc/simple-generator#26]
Some links to DC Laws are generating 403 "Forbidden" error pages:
http://www.openlims.org/public/L8-261.pdf

**Comment by FiestaJames** [comment]
This happens with D.C. Law 10-151: http://www.openlims.org/public/L10-151.pdf

**Comment by FiestaJames** [comment]
And D.C. Law 10-119: http://www.openlims.org/public/L10-119.pdf

**Comment by tmcw** [comment]
Thanks for the report - this repo has now generated redirects to the improved official copy of the law, so closing out issues.
